### ISSUE TITLE
Not unlocking properly with locked empty folder

### ISSUE THREAD

**Issue by evavh** [dvdsk/Book-safe#8]
When an empty folder is set to be locked, the unlock doesn't work properly. The program prints "no files to unlock" and "unlocking sync". The sync doesn't always unblock, and the Locked Books pdf is not removed.

**Comment by yara-blue** [comment]
Can you check if there are still files in the `locked_books` directory after such a failed unlock? (there should be)

**Comment by evavh** [comment]
There are no files in the locked_books directory, probably because no books were locked in this case.

**Comment by yara-blue** [comment]
okay so I think I know what happens here:

1. Sync is disabled as part of locking
2. There is no content to lock so nothing is moved to `locked_books`
3. To check if we actually need to `unlock()` we check if there is content in `locked_books`
4. There is no content as nothing was moved thus `unlock()` does not continue
=> sync stays blocked

**Comment by yara-blue** [comment]
As a user, would you like sync to still be blocked if a empty dir is locked?

Otherwise a check (and early return if there is no content to block) in lock() just [before we start the pdf](https://github.com/dvdsk/Book-safe/blob/ef5938e857037cf1fa6ea192920bdf4ab3211796/src/main.rs#L175) gen would suffice.

We could just check if the length of the `to_lock` Vec is empty.
